### ISSUE TITLE
Need to provide dimension information to inform decomposition

### ISSUE THREAD

**Issue by gwemon** [i-adopt/variables#2]
Even though I-ADOPT does not cover units and dimension, I think that it is important that the property be defined with a knowledge of the dimension or most common units used for the variable. Otherwise it can be too much of a guess. Should we ask for this to be added when we submit an example for decomposition? Also a link to a publication or webpage describing the variable would be useful.

**Comment by mabablue** [comment]
I fully agree and I will add a template for submitting an issue
